using Avalonia; using Avalonia.Controls; using Avalonia.Layout; using Avalonia.Media; using Avalonia.Interactivity;
namespace ClickCore.Mac;
public sealed class MainWindow : Window
{
    readonly MacSettings settings; readonly ContentControl host = new(); readonly TextBlock title = new(); readonly TextBlock status = new();
    static readonly Color Accent=Color.Parse("#8B5CF6"), Surface=Color.Parse("#171525");
    public MainWindow(){ settings=SettingsStore.Load(); Title="ClickCore for macOS"; Width=1100; Height=700; MinWidth=850; MinHeight=560; Background=new SolidColorBrush(Color.Parse("#0D0B14")); Content=Shell(); Open(settings.SelectedPage); Closing+=(_,_)=>SettingsStore.Save(settings); }
    Control Shell(){ var nav=new StackPanel(); var brand=new StackPanel{Spacing=2,Margin=new Thickness(20,24,20,24)}; brand.Children.Add(new TextBlock{Text="CLICKCORE",FontSize=22,FontWeight=FontWeight.Bold,Foreground=new SolidColorBrush(Accent)}); brand.Children.Add(new TextBlock{Text="macOS edition",Foreground=Brushes.Gray}); nav.Children.Add(brand); foreach(var p in new[]{"Clicker","MS Gen","Macro","Optimizer","Appearance","About"}){var b=new Button{Content=p,Tag=p,HorizontalContentAlignment=HorizontalAlignment.Left,Padding=new Thickness(16,11),Margin=new Thickness(12,2),Background=Brushes.Transparent}; b.Click+=Nav; nav.Children.Add(b);} nav.Children.Add(new TextBlock{Text="macOS safety mode\n\nClick injection and global hooks are unavailable until a native permission-aware implementation is added.",TextWrapping=TextWrapping.Wrap,Foreground=Brushes.Gray,FontSize=11,Margin=new Thickness(20,30,20,0)}); var side=new Border{Background=new SolidColorBrush(Surface),Width=220,Child=nav}; title.FontSize=26; title.FontWeight=FontWeight.Bold; status.Foreground=Brushes.Orange; status.Text="Ready · no native input permissions requested"; status.TextWrapping=TextWrapping.Wrap; var head=new StackPanel{Spacing=8,Margin=new Thickness(34,28,34,12)}; head.Children.Add(title); head.Children.Add(status); var content=new DockPanel(); DockPanel.SetDock(head,Dock.Top); content.Children.Add(head); host.Margin=new Thickness(34,10,34,30); content.Children.Add(host); var root=new Grid(); root.ColumnDefinitions.Add(new ColumnDefinition(new GridLength(220))); root.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star)); Grid.SetColumn(side,0); Grid.SetColumn(content,1); root.Children.Add(side); root.Children.Add(content); return root; }
    void Nav(object? s,RoutedEventArgs e){if(s is Button{Tag:string p})Open(p);}
    void Open(string p){settings.SelectedPage=p; title.Text=p; host.Content=p switch{"Clicker"=>Clicker(),"MS Gen"=>Info("MS Gen","Microsoft-generation helpers","Windows-only integrations are not available on macOS. This page is informational rather than emulating those APIs."),"Macro"=>Info("Macro","Macro workspace","Recording and playback require global input hooks. Add the required macOS Input Monitoring permission before implementing a native provider."),"Optimizer"=>Info("Optimizer","Optimizer","Windows memory, timer-resolution, and network operations are not run on macOS. Your system remains unchanged."),"Appearance"=>Appearance(),"About"=>Info("About ClickCore","A cross-platform shell","ClickCore.Mac is an Avalonia .NET 8 port. Settings are stored in ~/Library/Application Support/ClickCore/settings.json. Native click injection and global hooks are deliberately reported as unavailable."),_=>Info(p,p,"Not available.")};}
    Control Clicker(){var cps=new NumericUpDown{Minimum=1,Maximum=1000,Value=(decimal)settings.ClicksPerSecond,Width=140}; cps.ValueChanged+=(_,_)=>{if(cps.Value is decimal v){settings.ClicksPerSecond=(double)v;SettingsStore.Save(settings);}}; var save=new Button{Content="Save settings",Padding=new Thickness(14,8),HorizontalAlignment=HorizontalAlignment.Left}; save.Click+=(_,_)=>{SettingsStore.Save(settings);status.Text=$"Saved to {SettingsStore.FilePath}";status.Foreground=Brushes.LightGreen;}; var p=Card("Clicker"); p.Children.Add(new TextBlock{Text="Clicks per second",Margin=new Thickness(0,20,0,5)}); p.Children.Add(cps); p.Children.Add(new TextBlock{Text="Click injection is unavailable on this first macOS port. No fake native events are generated.",TextWrapping=TextWrapping.Wrap,Foreground=Brushes.Orange,Margin=new Thickness(0,20,0,18)}); p.Children.Add(save); return p;}
    Control Appearance(){var p=Card("Appearance");var c=new CheckBox{Content="Keep window on top",IsChecked=settings.AlwaysOnTop,Margin=new Thickness(0,20,0,8)};c.IsCheckedChanged+=(_,_)=>{settings.AlwaysOnTop=c.IsChecked==true;Topmost=settings.AlwaysOnTop;SettingsStore.Save(settings);};p.Children.Add(c);p.Children.Add(new TextBlock{Text="Theme: Dark (Avalonia Fluent)",Foreground=Brushes.Gray});return p;}
    Control Info(string h,string sub,string msg){var p=Card(h);p.Children.Add(new TextBlock{Text=sub,Foreground=Brushes.Gray,Margin=new Thickness(0,8,0,18)});p.Children.Add(new TextBlock{Text=msg,TextWrapping=TextWrapping.Wrap,FontSize=15});return p;}
    static StackPanel Card(string h){var p=new StackPanel{Spacing=6,Margin=new Thickness(24),Background=new SolidColorBrush(Surface),HorizontalAlignment=HorizontalAlignment.Stretch,VerticalAlignment=VerticalAlignment.Top};p.Children.Add(new TextBlock{Text=h,FontSize=20,FontWeight=FontWeight.Bold});return p;}
}

